-- INSERT INTO salads (name, ingredients, filename)
-- VALUES
--   ('Cesar Salad',
--   '1 head romaine heart(chopped), 2 oz. parmesan cheese (shredded), dash pepper (optional), croutons, Asiago Caesar dressing to taste',
--   'cesar-salad.jpg'),
--   ('Garden Salad',
--   '1 head romaine (chopped), 2 tomatoes (wedges), 1/4 cucumber (sliced), 1/2 cup mixed cherry tomatoes, 1 oz. red onion (thinly sliced), 2 oz. parmesan cheese (shaved), Add your favorite dressing',
--   'garden-salad.jpg'),
--   ('Easy Fruit Salad',
--   '1 pineapple (chopped), 1/2 carton strawberries (quartered), 1/2 pkg. green grapes, 1/2 pkg. red grapes, 3 kiwi (cut), 1 can mandarins (drained), 1 carton red raspberries, 1 carton blackberries, 1/4 cup honey, 2 Tbsp fresh lime juice',
--   'fruit-salad.jpg'),
--   ('Potato Salad',
--   '4 potatoes, 8 Tbsp mayonnaise, 2 tsp vinegar (optional), 1/2 Tbsp sugar, 1 cucumber (chopped), 2 boiled eggs, 2 ham slices (diced), salt and pepper (to taste),
--   potato-salad.jpg'),
--   ('BBQ Chicken Santa Fe Salad',
--   '2 bbq chicken thighs, iceberg lettuce, feta cheese, sweet corn, green olives, carrots (sliced), strawberries, salt and pepper, Add your favorite dressing',
--   'bbq-chicken-sf-salad.jpg');